var petDog ='rex';
var petCog ='pepper';
console.log(petCog);
console.log("Le nom de mon chien est : " + petDog);
console.log("Le nom de mon chien est : " , petDog);
console.log("Le nom de mon chat est : " + petCat);
console.log("Le nom de mon chat est : " ,petCat);
var catSound = "ronron";
var dogSound = "ouaf";
console.log(petDog, "dit", dogSound);
console.log(petCat, "dit", catSound);
catSound = "miaou";
console.log(petCat, "dit maintenant", catSound);
